[workspace.package]
rust-version = "1.83.0"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "bin/ress",
    "bin/reth",
    "crates/common",
    "crates/network",
    "crates/node",
    "crates/primitives",
    "crates/provider",
    "crates/subprotocol",
    "crates/vm",
]

# Explicitly set the resolver to version 2, which is the default for packages with edition >= 2021
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"

[workspace.lints.rust]
missing_debug_implementations = "warn"
missing_docs = "warn"
rust_2018_idioms = { level = "deny", priority = -1 }
unreachable_pub = "warn"
unused_must_use = "deny"

[workspace.lints.rustdoc]
all = "warn"


[workspace.dependencies]
# ress
ress-node = { path = "crates/node" }
ress-subprotocol = { path = "crates/subprotocol" }
ress-provider = { path = "crates/provider" }
ress-network = { path = "crates/network" }
ress-common = { path = "crates/common" }
ress-vm = { path = "crates/vm" }
ress-primitives = { path = "crates/primitives" }

# reth
reth = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }

## primitives/types
reth-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }

## db
reth-db = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", rev = "986c754", features = [
    "test-utils",
] }
## network
reth-eth-wire = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-network-api = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-network = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }

## trie
reth-trie = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-trie-sparse = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }

## evm
reth-revm = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }

## consensus
reth-engine-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-ethereum-engine-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-consensus = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-consensus-debug-client = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }

## rpc
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-rpc-engine-api = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-rpc-layer = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-rpc-types-compat = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-rpc-builder = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }

## node
reth-node-api = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-payload-builder = { git = "https://github.com/paradigmxyz/reth", rev = "986c754", features = [
    "test-utils",
] }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }

## util
reth-tokio-util = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }
reth-tasks = { git = "https://github.com/paradigmxyz/reth", rev = "986c754" }

# alloy
alloy-primitives = { version = "0.8.15", default-features = false }
alloy-eips = { version = "0.9.2", default-features = false }
alloy-rpc-types-eth = { version = "0.9.2", default-features = false }
alloy-rpc-types = { version = "0.9.2", default-features = false }
alloy-rpc-types-engine = { version = "0.9.2", default-features = false }
alloy-provider = { version = "0.9.2", default-features = false }
alloy-transport-http = { version = "0.9.2", default-features = false }
alloy-serde = { version = "0.9.2", default-features = false }
alloy-trie = { version = "0.7.8", default-features = false }
alloy-rlp = "0.3.10"

# misc
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.39", features = ["full"] }
tokio-stream = "0.1.11"
futures = "0.3"
eyre = "0.6"
rand = "0.8.5"
tracing = "0.1.0"
tracing-subscriber = "0.3"
thiserror = "2.0.9"
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
jsonrpsee-core = "0.24"
jsonrpsee-http-client = "0.24"
parking_lot = "0.12"
assert_matches = "1.5.0"
serde_json = "1.0.1"
reqwest = { version = "0.12", features = ["json"] }
dotenvy = "0.15.7"

# for now disk using sqlite
rusqlite = { version = "0.32.0", features = ["bundled"] }
