[workspace.package]
rust-version = "1.83.0"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/stateless", "crates/stateful", "crates/subprotocol"]

[workspace.dependencies]
stateless = { path = "crates/stateless" }
stateful = { path = "crates/stateful" }
ress-subprotocol = { path = "crates/subprotocol" }

clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.39", features = ["full"] }
tokio-stream = "0.1.11"
futures = "0.3"
eyre = "0.6"
rand = "0.8.5"
tracing = "0.1.0"
tracing-subscriber = "0.3"
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"


reth-eth-wire = { git = "https://github.com/paradigmxyz/reth", rev = "ef033abaf9105f167a778e00411e005ba9a0271e" }
reth-trie = { git = "https://github.com/paradigmxyz/reth", rev = "ef033abaf9105f167a778e00411e005ba9a0271e" }
reth-network = { git = "https://github.com/paradigmxyz/reth", rev = "ef033abaf9105f167a778e00411e005ba9a0271e" }
reth-network-api = { git = "https://github.com/paradigmxyz/reth", rev = "ef033abaf9105f167a778e00411e005ba9a0271e" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "ef033abaf9105f167a778e00411e005ba9a0271e" }
reth = { git = "https://github.com/paradigmxyz/reth", rev = "ef033abaf9105f167a778e00411e005ba9a0271e" }

alloy-primitives = { version = "0.8.11", default-features = false }
