[package]
name = "ress-primitives"
rust-version.workspace = true
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
alloy-primitives.workspace = true

# `serde` feature
serde = { workspace = true, optional = true }

[features]
serde = ["dep:serde"]
