[package]
name = "ress-common"
rust-version.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
reth.workspace = true
alloy-primitives.workspace = true

eyre.workspace = true
serde_json.workspace = true
