[package]
name = "ress-common"
rust-version.workspace = true
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
#reth
reth-primitives.workspace = true

# ress
ress-primitives = { workspace = true, features = ["serde"] }

# alloy
alloy-primitives.workspace = true
alloy-rpc-types-engine = { workspace = true, features = ["jwt", "serde"] }
alloy-provider.workspace = true
alloy-eips.workspace = true
alloy-transport-http.workspace = true

# reth
reth-network.workspace = true
reth-transaction-pool.workspace = true

# misc
eyre.workspace = true
serde_json.workspace = true
futures.workspace = true
