{
 "title": "Ress",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_network_connected_peers{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Canonical Head",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_engine_tree_head{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reth_db_table_size{instance=\"$instance\"})",
     "legendFormat": "{{table}}"
    }
   ]
  },
  { "title": "Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "New Payload V3 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=\"$instance\",quantile=\"0.5\"}",
     "legendFormat": "engine_newPayloadV3 p50"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "engine_newPayloadV3 p90"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "engine_newPayloadV3 p99"
    }
   ]
  },
  {
   "title": "Forkchoice Updated V3 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=\"$instance\",quantile=\"0.5\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 p50"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 p90"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 p99"
    }
   ]
  },
  {
   "title": "Block Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "reth_engine_tree_block_buffer_blocks{instance=\"$instance\"}",
     "legendFormat": "blocks"
    },
    {
     "expr": "reth_engine_tree_block_buffer_witnesses{instance=\"$instance\"}",
     "legendFormat": "witnesses"
    }
   ]
  },
  {
   "title": "Invalid Headers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "reth_consensus_engine_beacon_invalid_headers_count{instance=\"$instance\"}",
     "legendFormat": "count"
    }
   ]
  },
  { "title": "Engine Downloader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Inflight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "reth_engine_downloader_inflight{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(reth_engine_downloader_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Request Time p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_engine_downloader_elapsed{instance=\"$instance\",quantile=\"0.5\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Request Time p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_engine_downloader_elapsed{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}