[package]
name = "adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# alloy
alloy-rpc-types-engine = { workspace = true, features = ["serde"] }

tokio = { workspace = true, features = ["full"] }
bytes = "1.2"
hyper = { version = "1", features = ["full"] }
hyper-rustls = { version = "0.26", features = ["webpki-roots"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
serde_json.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures-util = "0.3"
