[package]
name = "ress-testing"
rust-version.workspace = true
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
# ress
ress-protocol.workspace = true

# reth
reth-storage-errors.workspace = true
reth-primitives.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-transport-http.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-debug.workspace = true

# misc
tokio.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
eyre.workspace = true
