[package]
name = "ress"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# ress
ress-protocol.workspace = true
ress-node.workspace = true
ress-common.workspace = true
ress-testing.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-provider.workspace = true

# reth
reth-rpc-api.workspace = true
reth-network.workspace = true
reth-network-api.workspace = true
reth-node-ethereum.workspace = true
reth-rpc-engine-api.workspace = true
reth-chainspec.workspace = true
reth-consensus-debug-client.workspace = true

# misc
clap.workspace = true
eyre.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber.workspace = true
rand.workspace = true
futures.workspace = true
parking_lot.workspace = true
assert_matches.workspace = true
dotenvy.workspace = true

[dev-dependencies]
reth-tokio-util.workspace = true
